code review and cleaning

diff --git a/ldap2zone/bin/ldap2bind b/ldap2zone/bin/ldap2bind
--- a/ldap2zone/bin/ldap2bind
+++ b/ldap2zone/bin/ldap2bind
@@ -1,5 +1,27 @@
 #!/bin/sh
 
+#######################################################################
+#
+# ldap2bind -- create flat dns zone from ldap 
+#
+# Copyright (c) 2008 by Cajus Pollmeier <pollmeier@gonicus.de>
+# Copyright (C) 2011 FusionDirectory project
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>
+#
+#######################################################################
+
 [ -r /etc/default/ldap2zone ] && . /etc/default/ldap2zone
 
 case "$LDAP_URI" in 
@@ -22,12 +44,12 @@ else ALLOW_NOTIFY=;
 fi
 
 if [ "$ALLOW_UPDATE" ]; then
-	ALLOW_UPDATE_PARAM="allow-update {$ALLOW_UPDATE};";
+  ALLOW_UPDATE_PARAM="allow-update {$ALLOW_UPDATE};";
 else ALLOW_UPDATE_PARAM=;
 fi
 
 if [ "$ALLOW_TRANSFER" ]; then
-	ALLOW_TRANSFER_PARAM="allow-transfer {$ALLOW_TRANSFER};";
+  ALLOW_TRANSFER_PARAM="allow-transfer {$ALLOW_TRANSFER};";
 else ALLOW_TRANSFER_PARAM=;
 fi
 
@@ -36,23 +58,23 @@ ldap2zone=`which ldap2zone`
 rndc=`which rndc`
 
 if [ -z "${ZONES}" ]; then
-	echo "No domains configured. Exiting..."
-	exit 0
+  echo "No domains configured. Exiting..."
+  exit 0
 fi
 
 if [ -z "${rndc}" ]; then
-	echo "rndc program not in $PATH. Exiting..."
-	exit 1
+  echo "rndc program not in $PATH. Exiting..."
+  exit 1
 fi
 
 if [ -z "${ldap2zone}" ]; then
-	echo "ldap2zone program not in $PATH. Exiting..."
-	exit 1
+  echo "ldap2zone program not in $PATH. Exiting..."
+  exit 1
 fi
 
 if [ ! -d $BIND_DIR ]; then
-	echo "The directory specified as $BIND_DIR does not exist. Exiting..."
-	exit 1
+  echo "The directory specified as $BIND_DIR does not exist. Exiting..."
+  exit 1
 fi
 
 if [ ! -d $BIND_DATA ]; then
@@ -62,31 +84,31 @@ fi
 
 
 if [ -w $BIND_DIR/named.conf.ldap2zone ]; then
-	>${BIND_DIR}/named.conf.ldap2zone
-	for domain in $ZONES; do
-		cat << EOF >> ${BIND_DIR}/named.conf.ldap2zone
+  >${BIND_DIR}/named.conf.ldap2zone
+  for domain in $ZONES; do
+    cat << EOF >> ${BIND_DIR}/named.conf.ldap2zone
 zone "${domain}" {
-	type master;
-	$ALLOW_NOTIFY
-	file "${BIND_DATA}/${PREFIX}${domain}";
-	$ALLOW_UPDATE_PARAM
-	$ALLOW_TRANSFER_PARAM
+  type master;
+  $ALLOW_NOTIFY
+  file "${BIND_DATA}/${PREFIX}${domain}";
+  $ALLOW_UPDATE_PARAM
+  $ALLOW_TRANSFER_PARAM
 };
 EOF
-	done
-	$rndc reconfig
+  done
+  $rndc reconfig
 fi
 
 for domain in $ZONES; do
-	if $ldap2zone $domain $LDAP_URI $TTL > /tmp/$domain; then
-		lines=$(cat /tmp/$domain | wc -l)
-		[ $lines -gt 1 ] && mv /tmp/$domain $BIND_DATA/${PREFIX}${domain}
-	fi
+  if $ldap2zone $domain $LDAP_URI $TTL > /tmp/$domain; then
+    lines=$(cat /tmp/$domain | wc -l)
+    [ $lines -gt 1 ] && mv /tmp/$domain $BIND_DATA/${PREFIX}${domain}
+  fi
 
-	result=$($rndc freeze $domain && $rndc reload $domain && $rndc thaw $domain 2>&1)
-	if [ $? -ne 0 ]; then
-		printf "Reloading the zone '$domain' failed: $result\n" 1>&2
-	else
-		printf "Reloading the zone '$domain' was successful\n" 1>&2
-	fi
+  result=$($rndc freeze $domain && $rndc reload $domain && $rndc thaw $domain 2>&1)
+  if [ $? -ne 0 ]; then
+    printf "Reloading the zone '$domain' failed: $result\n" 1>&2
+  else
+    printf "Reloading the zone '$domain' was successful\n" 1>&2
+  fi
 done
